Repository EditVR/editvr-frontend, pull requests merged in 2018-08, with the labels that each got.

#16 AFrame component re-rendering and state flattening.
  package.json
  src/actions/openExperience.test.js
  src/aframe/components/dialogPopup.container.js
  src/aframe/components/navLink.js
  src/aframe/components/spawnDialogs.js
  src/aframe/components/spawnLinks.js
  src/aframe/components/spawnSky.js
  src/aframe/entities/scene.js
  src/aframe/utils/connectRedux.js
  src/aframe/utils/connectRouter.js
  src/aframe/utils/shallowEqual.js
  src/aframe/utils/shallowEqual.test.js
  src/components/ComponentForm/ComponentForm.js
  src/components/SceneCards/SceneCards.js
  src/components/SceneCards/SceneCards.test.js
  src/components/SceneForm/SceneForm.js
  src/components/SceneForm/SceneForm.test.js
  src/lib/api/axiosInstance.js
  src/lib/parseComponentFromScene.js
  src/lib/parseComponentFromScene.test.js
  src/lib/parseExperience.test.js
  src/lib/parseSceneFromExperience.js
  src/lib/parseSceneFromExperience.test.js
  src/pages/VREditor/VREditor.js
  src/reducers/__snapshots__/openExperience.test.js.snap
  src/reducers/openExperience.js
  src/reducers/openExperience.test.js
  yarn.lock
Labels: ready for review

#15 FKED-43: Dialog Component Editing
  package.json
  src/actions/openExperience.js
  src/actions/openExperience.test.js
  src/aframe/components/dialogPopup.container.js
  src/aframe/components/navLink.js
  src/aframe/components/spawnDialogs.js
  src/aframe/components/spawnLinks.js
  src/aframe/components/spawnSky.js
  src/aframe/entities/scene.js
  src/aframe/utils/connectRedux.js
  src/aframe/utils/connectRouter.js
  src/aframe/utils/shallowEqual.js
  src/aframe/utils/shallowEqual.test.js
  src/components/ComponentForm/ComponentForm.container.js
  src/components/ComponentForm/ComponentForm.js
  src/components/ComponentForm/ComponentForm.style.js
  src/components/SceneCards/SceneCards.js
  src/components/SceneCards/SceneCards.test.js
  src/components/SceneForm/SceneForm.js
  src/components/SceneForm/SceneForm.test.js
  src/constants/api.js
  src/constants/openExperience.js
  src/lib/api/axiosInstance.js
  src/lib/api/component.js
  src/lib/api/component.test.js
  src/lib/api/index.js
  src/lib/api/scene.js
  src/lib/api/scene.test.js
  src/lib/parseComponentFromScene.js
  src/lib/parseComponentFromScene.test.js
  src/lib/parseExperience.test.js
  src/lib/parseSceneFromExperience.js
  src/lib/parseSceneFromExperience.test.js
  src/pages/VREditor/VREditor.js
  src/reducers/__snapshots__/openExperience.test.js.snap
  src/reducers/openExperience.js
  src/reducers/openExperience.test.js
  yarn.lock
Labels: ready for review

#17 FKED-45: Component dragging and dropping
  package.json
  src/actions/openExperience.js
  src/actions/openExperience.test.js
  src/aframe/components/clickDrag.js
  src/aframe/components/dialogPopup.container.js
  src/aframe/components/isDraggable.js
  src/aframe/components/isEditable.js
  src/aframe/components/spawnDialogs.js
  src/aframe/entities/scene.js
  src/components/ComponentForm/ComponentForm.js
  src/components/Loading/Loading.js
  src/components/Loading/Loading.style.js
  src/components/Loading/__snapshots__/Loading.test.js.snap
  src/components/ToolsMenu/ToolsMenu.js
  src/constants/modes.js
  src/pages/VREditor/VREditor.js
  yarn.lock
Labels: needs retroactive review, ready for review

#19 FKED-37: Link Component Creation
  package.json
  src/actions/openExperience.js
  src/aframe/components/simpleLink.container.js
  src/aframe/components/spawnComponents.js
  src/aframe/components/spawnLinks.js
  src/aframe/entities/scene.js
  src/components/ComponentCreateMenu/ComponentCreateMenu.js
  src/constants/component.js
  src/lib/api/component.js
  yarn.lock
Labels: ready for review

#23 FKED-85: Catch errors on registration collisions
  src/actions/user.js
  src/components/RegisterForm/RegisterForm.js
  src/constants/errors.js
  src/lib/actionGenerator.js
  src/lib/actionGenerator.test.js
  src/lib/api/axiosInstance.js
Labels: needs tests, passes code review, passes functional review
